name: Deploy to GitHub Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  deploy:
    uses: "getpelican/pelican/.github/workflows/github_pages.yml@master"
    permissions:
      contents: "read"
      pages: "write"
      id-token: "write"
    with:
      settings: "publishconf.py"
      requirements: "-r requirements.txt"
      theme: "https://github.com/Pelican-Elegant/elegant.git"
      python: "3.11"
      # output-path: "__output__/"